@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Oct 12 22:38:05 +0800 2021
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim multi_cycle_cpu_behav -key {Behavioral:sim_1:Functional:multi_cycle_cpu} -tclbatch multi_cycle_cpu.tcl -view F:/design-for-mult-cycle-CPU-in-verilog/multi_cpu_design_phy/multi_cycle_cpu_behav1.wcfg -log simulate.log"
call xsim  multi_cycle_cpu_behav -key {Behavioral:sim_1:Functional:multi_cycle_cpu} -tclbatch multi_cycle_cpu.tcl -view F:/design-for-mult-cycle-CPU-in-verilog/multi_cpu_design_phy/multi_cycle_cpu_behav1.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
