# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/design-for-mult-cycle-CPU-in-verilog/multi_cpu_design_phy/multi_cpu_design_phy.srcs/sources_1/ip/data_ram_phy/data_ram_phy.xci
# IP: The module: 'data_ram_phy' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/design-for-mult-cycle-CPU-in-verilog/multi_cpu_design_phy/multi_cpu_design_phy.srcs/sources_1/ip/data_ram_phy/data_ram_phy_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_ram_phy'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/design-for-mult-cycle-CPU-in-verilog/multi_cpu_design_phy/multi_cpu_design_phy.srcs/sources_1/ip/data_ram_phy/data_ram_phy.xci
# IP: The module: 'data_ram_phy' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/design-for-mult-cycle-CPU-in-verilog/multi_cpu_design_phy/multi_cpu_design_phy.srcs/sources_1/ip/data_ram_phy/data_ram_phy_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_ram_phy'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
